env: "local"
http_server:
  address: "0.0.0.0:8084"
  timeout: 4s
  idle_timeout: 60s
kafka:
  address: "localhost:29092"
DB:
  host: "localhost"
  port: "5433"
  name_db: "kafka_db"
  user_db: "kafka_user"
  password_db: "kafka_user"
