env: "local"
http_server:
  address: "localhost:8084"
  timeout: 4s
  idle_timeout: 60s
kafka:
  address: "localhost:29092"
postgresql:
  host: "localhost:5433"
  postgres_db: "kafka_db"
  postgres_user: "kafka_user"
  postgres_password: "kafka_user"
