package test

import (
	"clean/architector/internal/data/postgresql"
	"fmt"
)

func CreateListenerTable() string {
	fmt.Println("создаем БД")
	var connDb postgresql.IConnectionDb = postgresql.BuildConnPg()
	db := connDb.ConnDb()
	_, err := db.Exec("CREATE TABLE Listeners (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, name varchar(30) NOT NULL, host varchar(30) NOT NULL, port varchar(30) NOT NULL, status varchar(30) NOT NULL);")

	if err != nil {
		fmt.Println("Ошибка создания таблицы - " + err.Error())
		return "fail"
	}

	defer db.Close()

	return "success"
}
